[pytest]
DJANGO_SETTINGS_MODULE = cinema_service.settings

[flake8]
max-line-length = 88
extend-ignore = Q000,E203,W503
exclude =
    .git,
    __pycache__,
    .venv,
    venv,
    env,
    */migrations/*,
    */tests/*,
    manage.py
