# Generated by Django 5.1a1 on 2024-05-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
