# Generated by Django 4.1 on 2024-10-03 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
    ]
