# Generated by Django 4.1 on 2026-05-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="cinemahall",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["id"]},
        ),
    ]
