# Generated by Django 5.2 on 2025-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('movie_session', 'row', 'seat'), name='unique_ticket_seat_movie_session'),
        ),
    ]
