# Generated by Django 4.1 on 2025-08-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
