# Generated by Django 4.1 on 2023-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
