# Generated by Django 4.1 on 2023-07-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="cinema.order",
            ),
        ),
    ]
