# Generated by Django 4.1 on 2024-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
    ]
