# Generated by Django 5.2.7 on 2025-10-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_ticket_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_seat_movie_session",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "row", "movie_session")},
        ),
    ]
