# Generated by Django 4.1 on 2023-04-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_ticket_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_seat_movie_session",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("movie_session", "row", "seat")},
        ),
    ]
