# Generated by Django 4.1 on 2026-04-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_movie_session_seat_row',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('movie_session', 'row', 'seat')},
        ),
    ]
