# Generated by Django 4.1 on 2025-02-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_actor_options_alter_cinemahall_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id', 'title']},
        ),
    ]
