# Generated by Django 4.1 on 2024-08-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_ticket_options_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('row', 'seat')},
        ),
    ]
