# Generated by Django 4.1 on 2023-10-14 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0005_alter_movie_actors_alter_movie_genres_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("row", "seat")},
        ),
    ]
