# Generated by Django 4.1 on 2025-02-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
    ]
