# Generated by Django 4.1 on 2023-08-17 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0006_alter_moviesession_cinema_hall_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
    ]
