# Generated by Django 4.1 on 2024-05-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_alter_moviesession_cinema_hall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
