# Generated by Django 5.2.7 on 2025-10-22 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_remove_ticket_unique_seat_movie_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesession",
            name="show_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
