# Generated by Django 4.1 on 2023-04-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_remove_ticket_unique_ticket_seat_movie_session_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterField(
            model_name="ticket",
            name="movie_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="cinema.moviesession",
            ),
        ),
    ]
