# Generated by Django 4.1 on 2024-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0007_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesession",
            name="show_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "movie_session")},
        ),
    ]
